package com.sinaseyfi.remote

internal const val DATA = "data"
internal const val STATUS = "status"
internal const val TIMESTAMP = "timestamp"
internal const val ERROR_CODE = "errorCode"
internal const val ERROR_MESSAGE = "errorMessage"
internal const val ELAPSED = "elapsed"
internal const val CREDIT_COUNT = "creditCount"
internal const val ID = "id"
internal const val AVATAR_URL = "avatar_url"
internal const val LOGIN = "login"
internal const val NAME = "name"
internal const val STARGAZERS_COUNT = "stargazers_count"
internal const val FORKS = "forks"
internal const val OWNER = "owner"
internal const val SINCE = "since"
internal const val PRIVATE = "private"
internal const val HTML_URL = "html_url"
internal const val PERMISSIONS = "permissions"
internal const val PUSH = "push"
internal const val PULL = "pull"
internal const val ADMIN = "admin"
internal const val DESCRIPTION = "description"
internal const val REPO = "repo"
internal const val PER_PAGE = "per_page"
internal const val PAGE = "page"
internal const val AFFILIATION = "affiliation"